### ISSUE TITLE
global modifier in regex pattern

### ISSUE THREAD

**Issue by johnnysainz** [recurser/jquery-i18n#12]
Using numbered wildcards consecutively like so: '%1$s enabled %2$s %3$s' occasionally causes a match to miss, this results in the actual wildcard being displayed in the UI. After logging just about everything in the library, I decided to omit the 'global' modifier in the regex pattern on line 71 and viola, problem solved. 

I can't find too much information on when it's ok to NOT use the global modifier, but this guy (http://stackoverflow.com/a/1222089) thinks it's ok. 

This is my first time reporting an issue on github so I apologize in advance if it's not by the books.

**Comment by recurser** [comment]
@johnnysainz I'm going to close this - feel free to re-open it if you are still having problems.
