### ISSUE TITLE
Change language in javascript runtime

### ISSUE THREAD

**Issue by oscarml** [recurser/jquery-i18n#15]
Hello,

I'd like to know if it's posible to change the language at runtime, without refreshing the page.

I load the dictionary this way:
$.i18n.load('es');

And, if the user changes the language, I'd like to do something like:
$.i18n.unload('es');
$.i18n.load('en');

If this possible?

Thanks!

**Comment by recurser** [comment]
Hi @oscarml, apologies for the huge delay here. I've just released version `1.1.2` that explicitly supports this:

```javascript
$.i18n.load('en');
$.i18n.unload();
$.i18n.load('ja');
```

Behind the scenes it basically does what you described above, so you can keep doing that too if you'd prefer.
